fix-error in outdated json file

diff --git a/.github/workflows/auto-update-dependencies.yml b/.github/workflows/auto-update-dependencies.yml
--- a/.github/workflows/auto-update-dependencies.yml
+++ b/.github/workflows/auto-update-dependencies.yml
@@ -1,44 +1,44 @@
 name: Update Dependencies
 
 on:
- schedule:
-    - cron: '0 0 * * 0' 
- workflow_dispatch: 
+  schedule:
+    - cron: '0 0 * * 0'
+  workflow_dispatch:
 
 jobs:
- update:
+  update:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-    - name: Setup Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: '20' 
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20'
 
-    - name: Install dependencies
-      run: npm ci 
+      - name: Install dependencies
+        run: npm ci
 
-    - name: Check for updates
-      run: |
-        npm outdated --json > outdated.json
-        if [ -s outdated.json ]; then
-          echo "Updates found"
-          echo "::set-output name=updates_found::true"
-        else
-          echo "No updates found"
-          echo "::set-output name=updates_found::false"
-        fi
-      id: check
+      - name: Check for updates
+        run: |
+          npm outdated --json > outdated.json  || { echo "npm outdated failed with exit code $?"; exit 1; }
+          if [ -s outdated.json ]; then
+            echo "Updates found"
+            echo "::set-output name=updates_found::true"
+          else
+            echo "No updates found"
+            echo "::set-output name=updates_found::false"
+          fi
+        id: check
 
-    - name: Create Pull Request
-      if: steps.check.outputs.updates_found == 'true'
-      uses: peter-evans/create-pull-request@v3
-      with:
-        title: "Update dependencies"
-        body: "This PR updates the dependencies to their latest versions."
-        branch: "update-dependencies"
-        delete-branch: true
-        commit-message: "Update dependencies"
-        labels: "dependencies"
+      - name: Create Pull Request
+        if: steps.check.outputs.updates_found == 'true'
+        uses: peter-evans/create-pull-request@v3
+        with:
+          title: 'Update dependencies'
+          body: 'This PR updates the dependencies to their latest versions.'
+          branch: 'update-dependencies'
+          delete-branch: true
+          commit-message: 'Update dependencies'
+          labels: 'dependencies'
